// This file is auto-generated by @hey-api/openapi-ts

export const CreatePointOfInterestSchema = {
  properties: {
    Key: {
      type: 'string',
    },
    Name: {
      type: 'string',
    },
  },
} as const;

export const CreateUserSchema = {
  properties: {
    Email: {
      format: 'email',
      type: 'string',
    },
    Password: {
      minLength: 8,
      type: 'string',
    },
    Role: {
      default: 'user',
      enum: ['admin', 'staff', 'user'],
      type: 'string',
    },
  },
} as const;

export const ErrorResponseSchema = {
  properties: {
    details: {
      default:
        'The request could not be understood or was missing required parameters.',
      type: 'string',
    },
    error: {
      default: 'Bad Request',
      type: 'string',
    },
  },
} as const;

export const LoginRequestSchema = {
  properties: {
    Email: {
      format: 'email',
      type: 'string',
    },
    Password: {
      maxLength: 100,
      minLength: 6,
      type: 'string',
    },
  },
} as const;

export const PointOfInterestSchema = {
  properties: {
    ID: {
      format: 'uuid',
      type: 'string',
    },
    Key: {
      type: 'string',
    },
    Name: {
      type: 'string',
    },
  },
} as const;

export const RechargeTypeCountsSchema = {
  properties: {
    Items: {
      items: {
        additionalProperties: {
          type: 'integer',
        },
        properties: {
          Period: {
            type: 'string',
          },
        },
        type: 'object',
      },
      type: 'array',
    },
    Types: {
      items: {
        type: 'string',
      },
      type: 'array',
    },
  },
} as const;

export const ReportCustomerSchema = {
  properties: {
    Email: {
      format: 'email',
      type: 'string',
    },
    FirstName: {
      type: 'string',
    },
    PhoneNumber: {
      type: 'string',
    },
    RadiusUsername: {
      type: 'string',
    },
    Surname: {
      type: 'string',
    },
  },
} as const;

export const ReportCustomersSchema = {
  items: {
    properties: {
      Email: {
        format: 'email',
        type: 'string',
      },
      FirstName: {
        type: 'string',
      },
      PhoneNumber: {
        type: 'string',
      },
      RadiusUsername: {
        type: 'string',
      },
      Surname: {
        type: 'string',
      },
    },
  },
  type: 'array',
} as const;

export const ReportExpiringCustomerSchema = {
  properties: {
    Address: {
      type: 'string',
    },
    Email: {
      format: 'email',
      type: 'string',
    },
    Expiration: {
      type: 'string',
    },
    FirstName: {
      type: 'string',
    },
    LastPurchaseDuration: {
      type: 'string',
    },
    LastPurchaseSpeed: {
      type: 'string',
    },
    PhoneNumber: {
      type: 'string',
    },
    RadiusUsername: {
      type: 'string',
    },
    Surname: {
      type: 'string',
    },
  },
} as const;

export const ReportExpiringCustomersSchema = {
  items: {
    properties: {
      Address: {
        type: 'string',
      },
      Email: {
        format: 'email',
        type: 'string',
      },
      Expiration: {
        type: 'string',
      },
      FirstName: {
        type: 'string',
      },
      LastPurchaseDuration: {
        type: 'string',
      },
      LastPurchaseSpeed: {
        type: 'string',
      },
      PhoneNumber: {
        type: 'string',
      },
      RadiusUsername: {
        type: 'string',
      },
      Surname: {
        type: 'string',
      },
    },
  },
  type: 'array',
} as const;

export const ReportRechargeSchema = {
  properties: {
    Amount: {
      type: 'number',
    },
    BuildName: {
      type: 'string',
    },
    BuildType: {
      type: 'string',
    },
    DateCreated: {
      format: 'date-time',
      type: 'string',
    },
    Email: {
      format: 'email',
      type: 'string',
    },
    FirstName: {
      type: 'string',
    },
    ItemName: {
      type: 'string',
    },
    ServiceId: {
      format: 'int64',
      type: 'integer',
    },
    Successful: {
      type: 'boolean',
    },
    Surname: {
      type: 'string',
    },
  },
} as const;

export const ReportRechargeSummariesSchema = {
  items: {
    properties: {
      Amount: {
        type: 'number',
      },
      BuildName: {
        type: 'string',
      },
      BuildType: {
        type: 'string',
      },
      DateCreated: {
        format: 'date-time',
        type: 'string',
      },
      Email: {
        format: 'email',
        type: 'string',
      },
      FirstName: {
        type: 'string',
      },
      ItemName: {
        type: 'string',
      },
      ServiceId: {
        format: 'int64',
        type: 'integer',
      },
      Successful: {
        type: 'boolean',
      },
      Surname: {
        type: 'string',
      },
    },
  },
  type: 'array',
} as const;

export const ReportRechargeSummarySchema = {
  properties: {
    Amount: {
      type: 'number',
    },
    BuildName: {
      type: 'string',
    },
    BuildType: {
      type: 'string',
    },
    DateCreated: {
      format: 'date-time',
      type: 'string',
    },
    Email: {
      format: 'email',
      type: 'string',
    },
    FirstName: {
      type: 'string',
    },
    ItemName: {
      type: 'string',
    },
    ServiceId: {
      format: 'int64',
      type: 'integer',
    },
    Successful: {
      type: 'boolean',
    },
    Surname: {
      type: 'string',
    },
  },
} as const;

export const ReportRechargesSchema = {
  items: {
    properties: {
      Amount: {
        type: 'number',
      },
      BuildName: {
        type: 'string',
      },
      BuildType: {
        type: 'string',
      },
      DateCreated: {
        format: 'date-time',
        type: 'string',
      },
      Email: {
        format: 'email',
        type: 'string',
      },
      FirstName: {
        type: 'string',
      },
      ItemName: {
        type: 'string',
      },
      ServiceId: {
        format: 'int64',
        type: 'integer',
      },
      Successful: {
        type: 'boolean',
      },
      Surname: {
        type: 'string',
      },
    },
  },
  type: 'array',
} as const;

export const ReportSummariesSchema = {
  items: {
    properties: {
      AmountFee: {
        type: 'string',
      },
      AmountGross: {
        type: 'string',
      },
      AmountNet: {
        type: 'string',
      },
      BuildName: {
        type: 'string',
      },
      BuildType: {
        type: 'string',
      },
      CashAmount: {
        type: 'string',
      },
      CashCode: {
        type: 'string',
      },
      DateCreated: {
        format: 'date-time',
        type: 'string',
      },
      ItemName: {
        type: 'string',
      },
      RadiusUsername: {
        type: 'string',
      },
      ServiceId: {
        format: 'int64',
        type: 'integer',
      },
    },
  },
  type: 'array',
} as const;

export const ReportSummarySchema = {
  properties: {
    AmountFee: {
      type: 'string',
    },
    AmountGross: {
      type: 'string',
    },
    AmountNet: {
      type: 'string',
    },
    BuildName: {
      type: 'string',
    },
    BuildType: {
      type: 'string',
    },
    CashAmount: {
      type: 'string',
    },
    CashCode: {
      type: 'string',
    },
    DateCreated: {
      format: 'date-time',
      type: 'string',
    },
    ItemName: {
      type: 'string',
    },
    RadiusUsername: {
      type: 'string',
    },
    ServiceId: {
      format: 'int64',
      type: 'integer',
    },
  },
} as const;

export const SuccessResponseSchema = {
  properties: {
    data: {
      oneOf: [
        {
          properties: {
            Email: {
              format: 'email',
              type: 'string',
            },
            ID: {
              format: 'uuid',
              type: 'string',
            },
            MfaEnabled: {
              type: 'boolean',
            },
            MfaVerified: {
              type: 'boolean',
            },
            Role: {
              default: 'user',
              enum: ['admin', 'staff', 'user'],
              type: 'string',
            },
          },
        },
        {
          properties: {
            ID: {
              format: 'uuid',
              type: 'string',
            },
            Key: {
              type: 'string',
            },
            Name: {
              type: 'string',
            },
          },
        },
        {
          items: {
            properties: {
              Email: {
                format: 'email',
                type: 'string',
              },
              ID: {
                format: 'uuid',
                type: 'string',
              },
              MfaEnabled: {
                type: 'boolean',
              },
              MfaVerified: {
                type: 'boolean',
              },
              Role: {
                default: 'user',
                enum: ['admin', 'staff', 'user'],
                type: 'string',
              },
            },
          },
          type: 'array',
        },
        {
          items: {
            properties: {
              ID: {
                format: 'uuid',
                type: 'string',
              },
              Key: {
                type: 'string',
              },
              Name: {
                type: 'string',
              },
            },
          },
          type: 'array',
        },
        {
          properties: {
            Items: {
              items: {
                additionalProperties: {
                  type: 'integer',
                },
                properties: {
                  Period: {
                    type: 'string',
                  },
                },
                type: 'object',
              },
              type: 'array',
            },
            Types: {
              items: {
                type: 'string',
              },
              type: 'array',
            },
          },
        },
        {
          items: {
            properties: {
              RechargeCount: {
                type: 'integer',
              },
              RechargeMaxDate: {
                format: 'date-time',
                type: 'string',
              },
              RechargeName: {
                type: 'string',
              },
              RechargePeriod: {
                type: 'string',
              },
            },
          },
          type: 'array',
        },
        {
          properties: {
            Email: {
              format: 'email',
              type: 'string',
            },
            FirstName: {
              type: 'string',
            },
            PhoneNumber: {
              type: 'string',
            },
            RadiusUsername: {
              type: 'string',
            },
            Surname: {
              type: 'string',
            },
          },
        },
        {
          items: {
            properties: {
              Email: {
                format: 'email',
                type: 'string',
              },
              FirstName: {
                type: 'string',
              },
              PhoneNumber: {
                type: 'string',
              },
              RadiusUsername: {
                type: 'string',
              },
              Surname: {
                type: 'string',
              },
            },
          },
          type: 'array',
        },
        {
          properties: {
            Address: {
              type: 'string',
            },
            Email: {
              format: 'email',
              type: 'string',
            },
            Expiration: {
              type: 'string',
            },
            FirstName: {
              type: 'string',
            },
            LastPurchaseDuration: {
              type: 'string',
            },
            LastPurchaseSpeed: {
              type: 'string',
            },
            PhoneNumber: {
              type: 'string',
            },
            RadiusUsername: {
              type: 'string',
            },
            Surname: {
              type: 'string',
            },
          },
        },
        {
          items: {
            properties: {
              Address: {
                type: 'string',
              },
              Email: {
                format: 'email',
                type: 'string',
              },
              Expiration: {
                type: 'string',
              },
              FirstName: {
                type: 'string',
              },
              LastPurchaseDuration: {
                type: 'string',
              },
              LastPurchaseSpeed: {
                type: 'string',
              },
              PhoneNumber: {
                type: 'string',
              },
              RadiusUsername: {
                type: 'string',
              },
              Surname: {
                type: 'string',
              },
            },
          },
          type: 'array',
        },
        {
          properties: {
            Amount: {
              type: 'number',
            },
            BuildName: {
              type: 'string',
            },
            BuildType: {
              type: 'string',
            },
            DateCreated: {
              format: 'date-time',
              type: 'string',
            },
            Email: {
              format: 'email',
              type: 'string',
            },
            FirstName: {
              type: 'string',
            },
            ItemName: {
              type: 'string',
            },
            ServiceId: {
              format: 'int64',
              type: 'integer',
            },
            Successful: {
              type: 'boolean',
            },
            Surname: {
              type: 'string',
            },
          },
        },
        {
          items: {
            properties: {
              Amount: {
                type: 'number',
              },
              BuildName: {
                type: 'string',
              },
              BuildType: {
                type: 'string',
              },
              DateCreated: {
                format: 'date-time',
                type: 'string',
              },
              Email: {
                format: 'email',
                type: 'string',
              },
              FirstName: {
                type: 'string',
              },
              ItemName: {
                type: 'string',
              },
              ServiceId: {
                format: 'int64',
                type: 'integer',
              },
              Successful: {
                type: 'boolean',
              },
              Surname: {
                type: 'string',
              },
            },
          },
          type: 'array',
        },
        {
          properties: {
            Amount: {
              type: 'number',
            },
            BuildName: {
              type: 'string',
            },
            BuildType: {
              type: 'string',
            },
            DateCreated: {
              format: 'date-time',
              type: 'string',
            },
            Email: {
              format: 'email',
              type: 'string',
            },
            FirstName: {
              type: 'string',
            },
            ItemName: {
              type: 'string',
            },
            ServiceId: {
              format: 'int64',
              type: 'integer',
            },
            Successful: {
              type: 'boolean',
            },
            Surname: {
              type: 'string',
            },
          },
        },
        {
          items: {
            properties: {
              Amount: {
                type: 'number',
              },
              BuildName: {
                type: 'string',
              },
              BuildType: {
                type: 'string',
              },
              DateCreated: {
                format: 'date-time',
                type: 'string',
              },
              Email: {
                format: 'email',
                type: 'string',
              },
              FirstName: {
                type: 'string',
              },
              ItemName: {
                type: 'string',
              },
              ServiceId: {
                format: 'int64',
                type: 'integer',
              },
              Successful: {
                type: 'boolean',
              },
              Surname: {
                type: 'string',
              },
            },
          },
          type: 'array',
        },
        {
          properties: {
            AmountFee: {
              type: 'string',
            },
            AmountGross: {
              type: 'string',
            },
            AmountNet: {
              type: 'string',
            },
            BuildName: {
              type: 'string',
            },
            BuildType: {
              type: 'string',
            },
            CashAmount: {
              type: 'string',
            },
            CashCode: {
              type: 'string',
            },
            DateCreated: {
              format: 'date-time',
              type: 'string',
            },
            ItemName: {
              type: 'string',
            },
            RadiusUsername: {
              type: 'string',
            },
            ServiceId: {
              format: 'int64',
              type: 'integer',
            },
          },
        },
        {
          items: {
            properties: {
              AmountFee: {
                type: 'string',
              },
              AmountGross: {
                type: 'string',
              },
              AmountNet: {
                type: 'string',
              },
              BuildName: {
                type: 'string',
              },
              BuildType: {
                type: 'string',
              },
              CashAmount: {
                type: 'string',
              },
              CashCode: {
                type: 'string',
              },
              DateCreated: {
                format: 'date-time',
                type: 'string',
              },
              ItemName: {
                type: 'string',
              },
              RadiusUsername: {
                type: 'string',
              },
              ServiceId: {
                format: 'int64',
                type: 'integer',
              },
            },
          },
          type: 'array',
        },
      ],
    },
    details: {
      default: 'Operation completed successfully',
      type: 'string',
    },
    message: {
      default: 'Success',
      type: 'string',
    },
    pages: {
      default: 1,
      type: 'integer',
    },
  },
} as const;

export const UpdatePointOfInterestSchema = {
  properties: {
    Key: {
      type: 'string',
    },
    Name: {
      type: 'string',
    },
  },
} as const;

export const UpdateUserSchema = {
  properties: {
    Email: {
      format: 'email',
      type: 'string',
    },
    Role: {
      default: 'user',
      enum: ['admin', 'staff', 'user'],
      type: 'string',
    },
  },
} as const;

export const UserSchema = {
  properties: {
    Email: {
      format: 'email',
      type: 'string',
    },
    ID: {
      format: 'uuid',
      type: 'string',
    },
    MfaEnabled: {
      type: 'boolean',
    },
    MfaVerified: {
      type: 'boolean',
    },
    Role: {
      default: 'user',
      enum: ['admin', 'staff', 'user'],
      type: 'string',
    },
  },
} as const;
