// This file is auto-generated by @hey-api/openapi-ts

export type CreatePointOfInterest = {
  Key?: string;
  Name?: string;
};

export type CreateUser = {
  Email?: string;
  Password?: string;
  Role?: ['admin', 'staff', 'user'];
};

export type LoginRequest = {
  Email?: string;
  Password?: string;
};

export type PointOfInterest = {
  ID?: string;
  Key?: string;
  Name?: string;
};

export type UpdatePointOfInterest = {
  Key?: string;
  Name?: string;
};

export type UpdateUser = {
  Email?: string;
  Role?: ['admin', 'staff', 'user'];
};

export type User = {
  Email?: string;
  ID?: string;
  MfaEnabled?: boolean;
  MfaVerified?: boolean;
  Role?: ['admin', 'staff', 'user'];
};

export type ZingResponse = {
  data?:
    | {
        Email?: string;
        ID?: string;
        MfaEnabled?: boolean;
        MfaVerified?: boolean;
        Role?: ['admin', 'staff', 'user'];
      }
    | Array<{
        Email?: string;
        ID?: string;
        MfaEnabled?: boolean;
        MfaVerified?: boolean;
        Role?: ['admin', 'staff', 'user'];
      }>
    | {
        ID?: string;
        Key?: string;
        Name?: string;
      }
    | Array<{
        ID?: string;
        Key?: string;
        Name?: string;
      }>;
  details?: string;
  error?: string;
  pages?: number;
};

export type GetApiAuthenticationCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/authentication/check';
};

export type GetApiAuthenticationCheckErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type GetApiAuthenticationCheckError =
  GetApiAuthenticationCheckErrors[keyof GetApiAuthenticationCheckErrors];

export type GetApiAuthenticationCheckResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: ['admin', 'staff', 'user'];
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: ['admin', 'staff', 'user'];
        }>
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>;
    details?: string;
    error?: string;
    pages?: number;
  };
};

export type GetApiAuthenticationCheckResponse =
  GetApiAuthenticationCheckResponses[keyof GetApiAuthenticationCheckResponses];

export type PostApiAuthenticationLoginData = {
  body?: {
    Email?: string;
    Password?: string;
  };
  path?: never;
  query?: never;
  url: '/api/authentication/login';
};

export type PostApiAuthenticationLoginErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiAuthenticationLoginError =
  PostApiAuthenticationLoginErrors[keyof PostApiAuthenticationLoginErrors];

export type PostApiAuthenticationLoginResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type PostApiAuthenticationLoginResponse =
  PostApiAuthenticationLoginResponses[keyof PostApiAuthenticationLoginResponses];

export type PostApiAuthenticationLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/authentication/logout';
};

export type PostApiAuthenticationLogoutErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiAuthenticationLogoutError =
  PostApiAuthenticationLogoutErrors[keyof PostApiAuthenticationLogoutErrors];

export type PostApiAuthenticationLogoutResponses = {
  /**
   * The request was successful.
   */
  200: {
    details?: string;
    message?: string;
  };
};

export type PostApiAuthenticationLogoutResponse =
  PostApiAuthenticationLogoutResponses[keyof PostApiAuthenticationLogoutResponses];

export type PostApiAuthenticationMfaDisableData = {
  body?: {
    userId?: string;
  };
  path?: never;
  query?: never;
  url: '/api/authentication/mfa/disable';
};

export type PostApiAuthenticationMfaDisableErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiAuthenticationMfaDisableError =
  PostApiAuthenticationMfaDisableErrors[keyof PostApiAuthenticationMfaDisableErrors];

export type PostApiAuthenticationMfaDisableResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type PostApiAuthenticationMfaDisableResponse =
  PostApiAuthenticationMfaDisableResponses[keyof PostApiAuthenticationMfaDisableResponses];

export type GetApiAuthenticationMfaEnableData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/authentication/mfa/enable';
};

export type GetApiAuthenticationMfaEnableErrors = {
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type GetApiAuthenticationMfaEnableError =
  GetApiAuthenticationMfaEnableErrors[keyof GetApiAuthenticationMfaEnableErrors];

export type GetApiAuthenticationMfaEnableResponses = {
  201: unknown;
};

export type PostApiAuthenticationMfaVerifyData = {
  body?: {
    code?: string;
  };
  path?: never;
  query?: never;
  url: '/api/authentication/mfa/verify';
};

export type PostApiAuthenticationMfaVerifyErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiAuthenticationMfaVerifyError =
  PostApiAuthenticationMfaVerifyErrors[keyof PostApiAuthenticationMfaVerifyErrors];

export type PostApiAuthenticationMfaVerifyResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type PostApiAuthenticationMfaVerifyResponse =
  PostApiAuthenticationMfaVerifyResponses[keyof PostApiAuthenticationMfaVerifyResponses];

export type PostApiAuthenticationRegisterData = {
  body?: {
    Email?: string;
    Password?: string;
    Role?: ['admin', 'staff', 'user'];
  };
  path?: never;
  query?: never;
  url: '/api/authentication/register';
};

export type PostApiAuthenticationRegisterErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * The request could not be completed due to a conflict with the current state of the resource.
   */
  409: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiAuthenticationRegisterError =
  PostApiAuthenticationRegisterErrors[keyof PostApiAuthenticationRegisterErrors];

export type PostApiAuthenticationRegisterResponses = {
  /**
   * The resource has been successfully created.
   */
  201: unknown;
};

export type GetApiPoisData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    search?: string;
  };
  url: '/api/pois';
};

export type GetApiPoisErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type GetApiPoisError = GetApiPoisErrors[keyof GetApiPoisErrors];

export type GetApiPoisResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: Array<{
      [key: string]: unknown;
    }>;
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type GetApiPoisResponse = GetApiPoisResponses[keyof GetApiPoisResponses];

export type PostApiPoisData = {
  body?: {
    Key?: string;
    Name?: string;
  };
  path?: never;
  query?: never;
  url: '/api/pois';
};

export type PostApiPoisErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * The request could not be completed due to a conflict with the current state of the resource.
   */
  409: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiPoisError = PostApiPoisErrors[keyof PostApiPoisErrors];

export type PostApiPoisResponses = {
  /**
   * The request was successful.
   */
  201: {
    details?: string;
    message?: string;
  };
};

export type PostApiPoisResponse =
  PostApiPoisResponses[keyof PostApiPoisResponses];

export type DeleteApiPoisByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/pois/{id}';
};

export type DeleteApiPoisByIdErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * The requested resource could not be found. Please check the URL or contact support.
   */
  404: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type DeleteApiPoisByIdError =
  DeleteApiPoisByIdErrors[keyof DeleteApiPoisByIdErrors];

export type DeleteApiPoisByIdResponses = {
  /**
   * The request was successful.
   */
  200: {
    details?: string;
    message?: string;
  };
};

export type DeleteApiPoisByIdResponse =
  DeleteApiPoisByIdResponses[keyof DeleteApiPoisByIdResponses];

export type GetApiPoisByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/pois/{id}';
};

export type GetApiPoisByIdErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * The requested resource could not be found. Please check the URL or contact support.
   */
  404: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type GetApiPoisByIdError =
  GetApiPoisByIdErrors[keyof GetApiPoisByIdErrors];

export type GetApiPoisByIdResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type GetApiPoisByIdResponse =
  GetApiPoisByIdResponses[keyof GetApiPoisByIdResponses];

export type PutApiPoisByIdData = {
  body?: {
    Key?: string;
    Name?: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/pois/{id}';
};

export type PutApiPoisByIdErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * The requested resource could not be found. Please check the URL or contact support.
   */
  404: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PutApiPoisByIdError =
  PutApiPoisByIdErrors[keyof PutApiPoisByIdErrors];

export type PutApiPoisByIdResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type PutApiPoisByIdResponse =
  PutApiPoisByIdResponses[keyof PutApiPoisByIdResponses];

export type GetApiUsersData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    search?: string;
  };
  url: '/api/users';
};

export type GetApiUsersErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type GetApiUsersError = GetApiUsersErrors[keyof GetApiUsersErrors];

export type GetApiUsersResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: Array<{
      [key: string]: unknown;
    }>;
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type GetApiUsersResponse =
  GetApiUsersResponses[keyof GetApiUsersResponses];

export type PostApiUsersData = {
  body?: {
    Email?: string;
    Password?: string;
    Role?: ['admin', 'staff', 'user'];
  };
  path?: never;
  query?: never;
  url: '/api/users';
};

export type PostApiUsersErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * The request could not be completed due to a conflict with the current state of the resource.
   */
  409: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiUsersError = PostApiUsersErrors[keyof PostApiUsersErrors];

export type PostApiUsersResponses = {
  /**
   * The request was successful.
   */
  201: {
    details?: string;
    message?: string;
  };
};

export type PostApiUsersResponse =
  PostApiUsersResponses[keyof PostApiUsersResponses];

export type DeleteApiUsersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type DeleteApiUsersByIdErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * The requested resource could not be found. Please check the URL or contact support.
   */
  404: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type DeleteApiUsersByIdError =
  DeleteApiUsersByIdErrors[keyof DeleteApiUsersByIdErrors];

export type DeleteApiUsersByIdResponses = {
  /**
   * The request was successful.
   */
  200: {
    details?: string;
    message?: string;
  };
};

export type DeleteApiUsersByIdResponse =
  DeleteApiUsersByIdResponses[keyof DeleteApiUsersByIdResponses];

export type GetApiUsersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type GetApiUsersByIdErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * The requested resource could not be found. Please check the URL or contact support.
   */
  404: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type GetApiUsersByIdError =
  GetApiUsersByIdErrors[keyof GetApiUsersByIdErrors];

export type GetApiUsersByIdResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type GetApiUsersByIdResponse =
  GetApiUsersByIdResponses[keyof GetApiUsersByIdResponses];

export type PutApiUsersByIdData = {
  body?: {
    Email?: string;
    Role?: ['admin', 'staff', 'user'];
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type PutApiUsersByIdErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * The requested resource could not be found. Please check the URL or contact support.
   */
  404: {
    details?: string;
    error?: string;
  };
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PutApiUsersByIdError =
  PutApiUsersByIdErrors[keyof PutApiUsersByIdErrors];

export type PutApiUsersByIdResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type PutApiUsersByIdResponse =
  PutApiUsersByIdResponses[keyof PutApiUsersByIdResponses];

export type ClientOptions = {
  baseUrl: 'http://localhost:4000' | 'https://api.example.com' | (string & {});
};
