// This file is auto-generated by @hey-api/openapi-ts

export type CreatePointOfInterest = {
  Key?: string;
  Name?: string;
};

export type CreateUser = {
  Email?: string;
  Password?: string;
  Role?: 'admin' | 'staff' | 'user';
};

export type ErrorResponse = {
  details?: string;
  error?: string;
};

export type LoginRequest = {
  Email?: string;
  Password?: string;
};

export type PointOfInterest = {
  ID?: string;
  Key?: string;
  Name?: string;
};

export type RechargeTypeCounts = {
  Items?: Array<{
    Period?: string;
    [key: string]: number | string | undefined;
  }>;
  Types?: Array<string>;
};

export type SuccessResponse = {
  data?:
    | {
        Email?: string;
        ID?: string;
        MfaEnabled?: boolean;
        MfaVerified?: boolean;
        Role?: 'admin' | 'staff' | 'user';
      }
    | {
        ID?: string;
        Key?: string;
        Name?: string;
      }
    | Array<{
        Email?: string;
        ID?: string;
        MfaEnabled?: boolean;
        MfaVerified?: boolean;
        Role?: 'admin' | 'staff' | 'user';
      }>
    | Array<{
        ID?: string;
        Key?: string;
        Name?: string;
      }>
    | {
        Items?: Array<{
          Period?: string;
          [key: string]: number | string | undefined;
        }>;
        Types?: Array<string>;
      };
  details?: string;
  message?: string;
  pages?: number;
};

export type UpdatePointOfInterest = {
  Key?: string;
  Name?: string;
};

export type UpdateUser = {
  Email?: string;
  Role?: 'admin' | 'staff' | 'user';
};

export type User = {
  Email?: string;
  ID?: string;
  MfaEnabled?: boolean;
  MfaVerified?: boolean;
  Role?: 'admin' | 'staff' | 'user';
};

export type GetApiAnalyticsRechargeTypeCountsData = {
  body?: never;
  path?: never;
  query?: {
    count?: number;
    period?: string;
    poi?: string;
  };
  url: '/api/analytics/recharge-type-counts';
};

export type GetApiAnalyticsRechargeTypeCountsErrors = {
  /**
   * The user is not authenticated.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Internal server error
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type GetApiAnalyticsRechargeTypeCountsError =
  GetApiAnalyticsRechargeTypeCountsErrors[keyof GetApiAnalyticsRechargeTypeCountsErrors];

export type GetApiAnalyticsRechargeTypeCountsResponses = {
  /**
   * The recharge type counts for the specified date range
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type GetApiAnalyticsRechargeTypeCountsResponse =
  GetApiAnalyticsRechargeTypeCountsResponses[keyof GetApiAnalyticsRechargeTypeCountsResponses];

export type GetApiAuthenticationCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/authentication/check';
};

export type GetApiAuthenticationCheckErrors = {
  /**
   * The user is not authenticated.
   */
  401: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type GetApiAuthenticationCheckError =
  GetApiAuthenticationCheckErrors[keyof GetApiAuthenticationCheckErrors];

export type GetApiAuthenticationCheckResponses = {
  /**
   * The user is authenticated.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type GetApiAuthenticationCheckResponse =
  GetApiAuthenticationCheckResponses[keyof GetApiAuthenticationCheckResponses];

export type PostApiAuthenticationLoginData = {
  body?: {
    Email?: string;
    Password?: string;
  };
  path?: never;
  query?: never;
  url: '/api/authentication/login';
};

export type PostApiAuthenticationLoginErrors = {
  /**
   * Invalid request.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * Unauthorized.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiAuthenticationLoginError =
  PostApiAuthenticationLoginErrors[keyof PostApiAuthenticationLoginErrors];

export type PostApiAuthenticationLoginResponses = {
  /**
   * User logged in successfully.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type PostApiAuthenticationLoginResponse =
  PostApiAuthenticationLoginResponses[keyof PostApiAuthenticationLoginResponses];

export type PostApiAuthenticationLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/authentication/logout';
};

export type PostApiAuthenticationLogoutErrors = {
  /**
   * Unauthorized.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiAuthenticationLogoutError =
  PostApiAuthenticationLogoutErrors[keyof PostApiAuthenticationLogoutErrors];

export type PostApiAuthenticationLogoutResponses = {
  /**
   * User logged out successfully.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type PostApiAuthenticationLogoutResponse =
  PostApiAuthenticationLogoutResponses[keyof PostApiAuthenticationLogoutResponses];

export type PostApiAuthenticationMfaDisableData = {
  body?: {
    userId?: string;
  };
  path?: never;
  query?: never;
  url: '/api/authentication/mfa/disable';
};

export type PostApiAuthenticationMfaDisableErrors = {
  /**
   * Bad Request.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * Unauthorized.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiAuthenticationMfaDisableError =
  PostApiAuthenticationMfaDisableErrors[keyof PostApiAuthenticationMfaDisableErrors];

export type PostApiAuthenticationMfaDisableResponses = {
  /**
   * MFA disabled successfully.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type PostApiAuthenticationMfaDisableResponse =
  PostApiAuthenticationMfaDisableResponses[keyof PostApiAuthenticationMfaDisableResponses];

export type GetApiAuthenticationMfaEnableData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/authentication/mfa/enable';
};

export type GetApiAuthenticationMfaEnableErrors = {
  /**
   * Unauthorized.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type GetApiAuthenticationMfaEnableError =
  GetApiAuthenticationMfaEnableErrors[keyof GetApiAuthenticationMfaEnableErrors];

export type GetApiAuthenticationMfaEnableResponses = {
  201: unknown;
};

export type PostApiAuthenticationMfaVerifyData = {
  body?: {
    code?: string;
  };
  path?: never;
  query?: never;
  url: '/api/authentication/mfa/verify';
};

export type PostApiAuthenticationMfaVerifyErrors = {
  /**
   * Bad Request.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * Unauthorized.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiAuthenticationMfaVerifyError =
  PostApiAuthenticationMfaVerifyErrors[keyof PostApiAuthenticationMfaVerifyErrors];

export type PostApiAuthenticationMfaVerifyResponses = {
  /**
   * MFA code verified successfully.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type PostApiAuthenticationMfaVerifyResponse =
  PostApiAuthenticationMfaVerifyResponses[keyof PostApiAuthenticationMfaVerifyResponses];

export type PostApiAuthenticationRegisterData = {
  body?: {
    Email?: string;
    Password?: string;
    Role?: 'admin' | 'staff' | 'user';
  };
  path?: never;
  query?: never;
  url: '/api/authentication/register';
};

export type PostApiAuthenticationRegisterErrors = {
  /**
   * Bad Request.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * Conflict.
   */
  409: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiAuthenticationRegisterError =
  PostApiAuthenticationRegisterErrors[keyof PostApiAuthenticationRegisterErrors];

export type PostApiAuthenticationRegisterResponses = {
  /**
   * User registered successfully.
   */
  201: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type PostApiAuthenticationRegisterResponse =
  PostApiAuthenticationRegisterResponses[keyof PostApiAuthenticationRegisterResponses];

export type GetApiPoisData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    search?: string;
  };
  url: '/api/pois';
};

export type GetApiPoisErrors = {
  /**
   * Bad Request.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * Unauthorized.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type GetApiPoisError = GetApiPoisErrors[keyof GetApiPoisErrors];

export type GetApiPoisResponses = {
  /**
   * Points of interest retrieved successfully.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type GetApiPoisResponse = GetApiPoisResponses[keyof GetApiPoisResponses];

export type PostApiPoisData = {
  body?: {
    Key?: string;
    Name?: string;
  };
  path?: never;
  query?: never;
  url: '/api/pois';
};

export type PostApiPoisErrors = {
  /**
   * Bad Request.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * The user is not authenticated.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Conflict.
   */
  409: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiPoisError = PostApiPoisErrors[keyof PostApiPoisErrors];

export type PostApiPoisResponses = {
  /**
   * Point of interest created successfully.
   */
  201: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type PostApiPoisResponse =
  PostApiPoisResponses[keyof PostApiPoisResponses];

export type DeleteApiPoisByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/pois/{id}';
};

export type DeleteApiPoisByIdErrors = {
  /**
   * Bad Request.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * The user is not authenticated.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Point of interest not found.
   */
  404: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type DeleteApiPoisByIdError =
  DeleteApiPoisByIdErrors[keyof DeleteApiPoisByIdErrors];

export type DeleteApiPoisByIdResponses = {
  /**
   * Point of interest deleted successfully.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type DeleteApiPoisByIdResponse =
  DeleteApiPoisByIdResponses[keyof DeleteApiPoisByIdResponses];

export type GetApiPoisByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/pois/{id}';
};

export type GetApiPoisByIdErrors = {
  /**
   * Bad Request.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * Unauthorized.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Not Found.
   */
  404: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type GetApiPoisByIdError =
  GetApiPoisByIdErrors[keyof GetApiPoisByIdErrors];

export type GetApiPoisByIdResponses = {
  /**
   * Point of interest retrieved successfully.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type GetApiPoisByIdResponse =
  GetApiPoisByIdResponses[keyof GetApiPoisByIdResponses];

export type PutApiPoisByIdData = {
  body?: {
    Key?: string;
    Name?: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/pois/{id}';
};

export type PutApiPoisByIdErrors = {
  /**
   * Bad Request.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * Unauthorized.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Not Found.
   */
  404: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PutApiPoisByIdError =
  PutApiPoisByIdErrors[keyof PutApiPoisByIdErrors];

export type PutApiPoisByIdResponses = {
  /**
   * Point of interest updated successfully.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type PutApiPoisByIdResponse =
  PutApiPoisByIdResponses[keyof PutApiPoisByIdResponses];

export type GetApiUsersData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    search?: string;
  };
  url: '/api/users';
};

export type GetApiUsersErrors = {
  /**
   * Bad Request.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * Unauthorized.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type GetApiUsersError = GetApiUsersErrors[keyof GetApiUsersErrors];

export type GetApiUsersResponses = {
  /**
   * Users retrieved successfully.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type GetApiUsersResponse =
  GetApiUsersResponses[keyof GetApiUsersResponses];

export type PostApiUsersData = {
  body?: {
    Email?: string;
    Password?: string;
    Role?: 'admin' | 'staff' | 'user';
  };
  path?: never;
  query?: never;
  url: '/api/users';
};

export type PostApiUsersErrors = {
  /**
   * Bad Request.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * Unauthorized.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Conflict.
   */
  409: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PostApiUsersError = PostApiUsersErrors[keyof PostApiUsersErrors];

export type PostApiUsersResponses = {
  /**
   * User created successfully.
   */
  201: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type PostApiUsersResponse =
  PostApiUsersResponses[keyof PostApiUsersResponses];

export type DeleteApiUsersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type DeleteApiUsersByIdErrors = {
  /**
   * Unauthorized.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * Not Found.
   */
  404: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type DeleteApiUsersByIdError =
  DeleteApiUsersByIdErrors[keyof DeleteApiUsersByIdErrors];

export type DeleteApiUsersByIdResponses = {
  /**
   * User deleted successfully.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type DeleteApiUsersByIdResponse =
  DeleteApiUsersByIdResponses[keyof DeleteApiUsersByIdResponses];

export type GetApiUsersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type GetApiUsersByIdErrors = {
  /**
   * Bad Request.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * Unauthorized.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * User not found.
   */
  404: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type GetApiUsersByIdError =
  GetApiUsersByIdErrors[keyof GetApiUsersByIdErrors];

export type GetApiUsersByIdResponses = {
  /**
   * User retrieved successfully.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type GetApiUsersByIdResponse =
  GetApiUsersByIdResponses[keyof GetApiUsersByIdResponses];

export type PutApiUsersByIdData = {
  body?: {
    Email?: string;
    Role?: 'admin' | 'staff' | 'user';
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type PutApiUsersByIdErrors = {
  /**
   * Bad Request.
   */
  400: {
    details?: string;
    error?: string;
  };
  /**
   * Unauthorized.
   */
  401: {
    details?: string;
    error?: string;
  };
  /**
   * User not found.
   */
  404: {
    details?: string;
    error?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    details?: string;
    error?: string;
  };
  default: unknown;
};

export type PutApiUsersByIdError =
  PutApiUsersByIdErrors[keyof PutApiUsersByIdErrors];

export type PutApiUsersByIdResponses = {
  /**
   * User updated successfully.
   */
  200: {
    data?:
      | {
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }
      | {
          ID?: string;
          Key?: string;
          Name?: string;
        }
      | Array<{
          Email?: string;
          ID?: string;
          MfaEnabled?: boolean;
          MfaVerified?: boolean;
          Role?: 'admin' | 'staff' | 'user';
        }>
      | Array<{
          ID?: string;
          Key?: string;
          Name?: string;
        }>
      | {
          Items?: Array<{
            Period?: string;
            [key: string]: number | string | undefined;
          }>;
          Types?: Array<string>;
        };
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type PutApiUsersByIdResponse =
  PutApiUsersByIdResponses[keyof PutApiUsersByIdResponses];

export type ClientOptions = {
  baseUrl: 'http://localhost:4000' | 'https://api.example.com' | (string & {});
};
