// This file is auto-generated by @hey-api/openapi-ts

export type LoginRequest = {
  Email?: string;
  Password?: string;
};

export type PointOfInterest = {
  ID?: string;
  Key?: string;
  Name?: string;
};

export type User = {
  Email?: string;
  ID?: string;
  MfaEnabled?: boolean;
  MfaVerified?: boolean;
  Role?: ['admin', 'staff', 'user'];
};

export type GetApiAuthenticationCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/authentication/check';
};

export type GetApiAuthenticationCheckErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  default: unknown;
};

export type GetApiAuthenticationCheckResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      Email?: string;
      ID?: string;
      MfaEnabled?: boolean;
      MfaVerified?: boolean;
      Role?: ['admin', 'staff', 'user'];
    };
    details?: string;
    message?: string;
  };
};

export type GetApiAuthenticationCheckResponse =
  GetApiAuthenticationCheckResponses[keyof GetApiAuthenticationCheckResponses];

export type PostApiAuthenticationLoginData = {
  body?: {
    Email?: string;
    Password?: string;
  };
  path?: never;
  query?: never;
  url: '/api/authentication/login';
};

export type PostApiAuthenticationLoginErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: unknown;
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type PostApiAuthenticationLoginResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type PostApiAuthenticationLoginResponse =
  PostApiAuthenticationLoginResponses[keyof PostApiAuthenticationLoginResponses];

export type PostApiAuthenticationLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/authentication/logout';
};

export type PostApiAuthenticationLogoutErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: unknown;
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type PostApiAuthenticationLogoutResponses = {
  /**
   * The request was successful.
   */
  200: {
    details?: string;
    message?: string;
  };
};

export type PostApiAuthenticationLogoutResponse =
  PostApiAuthenticationLogoutResponses[keyof PostApiAuthenticationLogoutResponses];

export type PostApiAuthenticationMfaDisableData = {
  body?: {
    userId?: string;
  };
  path?: never;
  query?: never;
  url: '/api/authentication/mfa/disable';
};

export type PostApiAuthenticationMfaDisableErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type PostApiAuthenticationMfaDisableResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type PostApiAuthenticationMfaDisableResponse =
  PostApiAuthenticationMfaDisableResponses[keyof PostApiAuthenticationMfaDisableResponses];

export type GetApiAuthenticationMfaEnableData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/authentication/mfa/enable';
};

export type GetApiAuthenticationMfaEnableErrors = {
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type GetApiAuthenticationMfaEnableResponses = {
  201: unknown;
};

export type PostApiAuthenticationMfaVerifyData = {
  body?: {
    code?: string;
  };
  path?: never;
  query?: never;
  url: '/api/authentication/mfa/verify';
};

export type PostApiAuthenticationMfaVerifyErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: unknown;
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type PostApiAuthenticationMfaVerifyResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type PostApiAuthenticationMfaVerifyResponse =
  PostApiAuthenticationMfaVerifyResponses[keyof PostApiAuthenticationMfaVerifyResponses];

export type PostApiAuthenticationRegisterData = {
  body?: {
    email?: string;
    password?: string;
    role?: ['admin', 'staff', 'user'];
  };
  path?: never;
  query?: never;
  url: '/api/authentication/register';
};

export type PostApiAuthenticationRegisterErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: unknown;
  /**
   * The request could not be completed due to a conflict with the current state of the resource.
   */
  409: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type PostApiAuthenticationRegisterResponses = {
  /**
   * The resource has been successfully created.
   */
  201: unknown;
};

export type GetApiPoisData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
  };
  url: '/api/pois';
};

export type GetApiPoisErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type GetApiPoisResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: Array<{
      [key: string]: unknown;
    }>;
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type GetApiPoisResponse = GetApiPoisResponses[keyof GetApiPoisResponses];

export type PostApiPoisData = {
  /**
   * Point Of Interest creation request body
   */
  body: {
    key?: string;
    name?: string;
  };
  path?: never;
  query?: never;
  url: '/api/pois';
};

export type PostApiPoisErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: unknown;
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  /**
   * The request could not be completed due to a conflict with the current state of the resource.
   */
  409: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type PostApiPoisResponses = {
  /**
   * The request was successful.
   */
  201: {
    details?: string;
    message?: string;
  };
};

export type PostApiPoisResponse =
  PostApiPoisResponses[keyof PostApiPoisResponses];

export type DeleteApiPoisByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/pois/{id}';
};

export type DeleteApiPoisByIdErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  /**
   * The requested resource could not be found. Please check the URL or contact support.
   */
  404: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type DeleteApiPoisByIdResponses = {
  /**
   * The request was successful.
   */
  200: {
    details?: string;
    message?: string;
  };
};

export type DeleteApiPoisByIdResponse =
  DeleteApiPoisByIdResponses[keyof DeleteApiPoisByIdResponses];

export type GetApiPoisByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/pois/{id}';
};

export type GetApiPoisByIdErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  /**
   * The requested resource could not be found. Please check the URL or contact support.
   */
  404: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type GetApiPoisByIdResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type GetApiPoisByIdResponse =
  GetApiPoisByIdResponses[keyof GetApiPoisByIdResponses];

export type PutApiPoisByIdData = {
  body?: {
    ID?: string;
    Key?: string;
    Name?: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/pois/{id}';
};

export type PutApiPoisByIdErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: unknown;
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  /**
   * The requested resource could not be found. Please check the URL or contact support.
   */
  404: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type PutApiPoisByIdResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type PutApiPoisByIdResponse =
  PutApiPoisByIdResponses[keyof PutApiPoisByIdResponses];

export type GetApiUsersData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
  };
  url: '/api/users';
};

export type GetApiUsersErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type GetApiUsersResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: Array<{
      [key: string]: unknown;
    }>;
    details?: string;
    message?: string;
    pages?: number;
  };
};

export type GetApiUsersResponse =
  GetApiUsersResponses[keyof GetApiUsersResponses];

export type PostApiUsersData = {
  /**
   * User creation request body
   */
  body: {
    email?: string;
    password?: string;
    role?: 'admin' | 'staff' | 'user';
  };
  path?: never;
  query?: never;
  url: '/api/users';
};

export type PostApiUsersErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: unknown;
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  /**
   * The request could not be completed due to a conflict with the current state of the resource.
   */
  409: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type PostApiUsersResponses = {
  /**
   * The request was successful.
   */
  201: {
    details?: string;
    message?: string;
  };
};

export type PostApiUsersResponse =
  PostApiUsersResponses[keyof PostApiUsersResponses];

export type DeleteApiUsersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type DeleteApiUsersByIdErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  /**
   * The requested resource could not be found. Please check the URL or contact support.
   */
  404: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type DeleteApiUsersByIdResponses = {
  /**
   * The request was successful.
   */
  200: {
    details?: string;
    message?: string;
  };
};

export type DeleteApiUsersByIdResponse =
  DeleteApiUsersByIdResponses[keyof DeleteApiUsersByIdResponses];

export type GetApiUsersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type GetApiUsersByIdErrors = {
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  /**
   * The requested resource could not be found. Please check the URL or contact support.
   */
  404: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type GetApiUsersByIdResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type GetApiUsersByIdResponse =
  GetApiUsersByIdResponses[keyof GetApiUsersByIdResponses];

export type PutApiUsersByIdData = {
  body?: {
    Email?: string;
    ID?: string;
    MfaEnabled?: boolean;
    MfaVerified?: boolean;
    Role?: ['admin', 'staff', 'user'];
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type PutApiUsersByIdErrors = {
  /**
   * The request could not be understood or was missing required parameters.
   */
  400: unknown;
  /**
   * You are not authorized to access this resource. Please log in or contact support.
   */
  401: unknown;
  /**
   * The requested resource could not be found. Please check the URL or contact support.
   */
  404: unknown;
  /**
   * An unexpected error occurred. Please try again later or contact support.
   */
  500: unknown;
  default: unknown;
};

export type PutApiUsersByIdResponses = {
  /**
   * The request was successful.
   */
  200: {
    data?: {
      [key: string]: unknown;
    };
    details?: string;
    message?: string;
  };
};

export type PutApiUsersByIdResponse =
  PutApiUsersByIdResponses[keyof PutApiUsersByIdResponses];

export type ClientOptions = {
  baseUrl: 'http://localhost:4000' | 'https://api.example.com' | (string & {});
};
