CREATE TABLE
    `radacct` (
        `radacctid` bigint (21) NOT NULL AUTO_INCREMENT,
        `acctsessionid` varchar(64) NOT NULL DEFAULT '',
        `acctuniqueid` varchar(32) NOT NULL DEFAULT '',
        `username` varchar(64) NOT NULL DEFAULT '',
        `groupname` varchar(64) NOT NULL DEFAULT '',
        `realm` varchar(64) DEFAULT '',
        `nasipaddress` varchar(15) NOT NULL DEFAULT '',
        `nasportid` varchar(15) DEFAULT NULL,
        `nasporttype` varchar(32) DEFAULT NULL,
        `acctstarttime` datetime DEFAULT NULL,
        `acctstoptime` datetime DEFAULT NULL,
        `acctsessiontime` int (12) DEFAULT NULL,
        `acctauthentic` varchar(32) DEFAULT NULL,
        `connectinfo_start` varchar(50) DEFAULT NULL,
        `connectinfo_stop` varchar(50) DEFAULT NULL,
        `acctinputoctets` bigint (20) DEFAULT NULL,
        `acctoutputoctets` bigint (20) DEFAULT NULL,
        `calledstationid` varchar(50) NOT NULL DEFAULT '',
        `callingstationid` varchar(50) NOT NULL DEFAULT '',
        `acctterminatecause` varchar(32) NOT NULL DEFAULT '',
        `servicetype` varchar(32) DEFAULT NULL,
        `framedprotocol` varchar(32) DEFAULT NULL,
        `framedipaddress` varchar(15) NOT NULL DEFAULT '',
        `acctstartdelay` int (12) DEFAULT NULL,
        `acctstopdelay` int (12) DEFAULT NULL,
        `xascendsessionsvrkey` varchar(10) DEFAULT NULL,
        `_accttime` datetime DEFAULT NULL,
        `_srvid` int (11) DEFAULT NULL,
        `_dailynextsrvactive` tinyint (1) DEFAULT NULL,
        `_apid` int (11) DEFAULT NULL,
        `qcreated` tinyint (1) NOT NULL,
        PRIMARY KEY (`radacctid`),
        KEY `username` (`username`),
        KEY `framedipaddress` (`framedipaddress`),
        KEY `acctsessionid` (`acctsessionid`),
        KEY `acctsessiontime` (`acctsessiontime`),
        KEY `acctuniqueid` (`acctuniqueid`),
        KEY `acctstarttime` (`acctstarttime`),
        KEY `acctstoptime` (`acctstoptime`),
        KEY `nasipaddress` (`nasipaddress`),
        KEY `_AcctTime` (`_accttime`),
        KEY `callingstationid` (`callingstationid`)
    ) ENGINE = InnoDB AUTO_INCREMENT = 1796077 DEFAULT CHARSET = utf8;