CREATE TABLE
    `rm_managers` (
        `managername` varchar(64) NOT NULL,
        `password` varchar(32) NOT NULL,
        `firstname` varchar(50) NOT NULL,
        `lastname` varchar(50) NOT NULL,
        `phone` varchar(15) NOT NULL,
        `mobile` varchar(15) NOT NULL,
        `address` varchar(50) NOT NULL,
        `city` varchar(50) NOT NULL,
        `zip` varchar(8) NOT NULL,
        `country` varchar(50) NOT NULL,
        `state` varchar(50) NOT NULL,
        `comment` varchar(200) NOT NULL,
        `company` varchar(50) NOT NULL,
        `vatid` varchar(40) NOT NULL,
        `email` varchar(50) NOT NULL,
        `balance` decimal(20, 2) NOT NULL,
        `perm_listusers` tinyint (1) NOT NULL,
        `perm_createusers` tinyint (1) NOT NULL,
        `perm_editusers` tinyint (1) NOT NULL,
        `perm_edituserspriv` tinyint (1) NOT NULL,
        `perm_deleteusers` tinyint (1) NOT NULL,
        `perm_listmanagers` tinyint (1) NOT NULL,
        `perm_createmanagers` tinyint (1) NOT NULL,
        `perm_editmanagers` tinyint (1) NOT NULL,
        `perm_deletemanagers` tinyint (1) NOT NULL,
        `perm_listservices` tinyint (1) NOT NULL,
        `perm_createservices` tinyint (1) NOT NULL,
        `perm_editservices` tinyint (1) NOT NULL,
        `perm_deleteservices` tinyint (1) NOT NULL,
        `perm_listonlineusers` tinyint (1) NOT NULL,
        `perm_listinvoices` tinyint (1) NOT NULL,
        `perm_trafficreport` tinyint (1) NOT NULL,
        `perm_addcredits` tinyint (1) NOT NULL,
        `perm_negbalance` tinyint (1) NOT NULL,
        `perm_listallinvoices` tinyint (1) NOT NULL,
        `perm_showinvtotals` tinyint (1) NOT NULL,
        `perm_logout` tinyint (1) NOT NULL,
        `perm_cardsys` tinyint (1) NOT NULL,
        `perm_editinvoice` tinyint (1) NOT NULL,
        `perm_allusers` tinyint (1) NOT NULL,
        `perm_allowdiscount` tinyint (1) NOT NULL,
        `perm_enwriteoff` tinyint (1) NOT NULL,
        `perm_accessap` tinyint (1) NOT NULL,
        `perm_cts` tinyint (1) NOT NULL,
        `perm_email` tinyint (1) NOT NULL,
        `perm_sms` tinyint (1) NOT NULL,
        `enablemanager` tinyint (1) NOT NULL,
        `lang` varchar(30) NOT NULL,
        PRIMARY KEY (`managername`)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8;