CREATE TABLE
    `rm_services` (
        `srvid` int (11) NOT NULL,
        `srvname` varchar(50) NOT NULL,
        `descr` varchar(255) NOT NULL,
        `downrate` int (11) NOT NULL,
        `uprate` int (11) NOT NULL,
        `limitdl` tinyint (1) NOT NULL,
        `limitul` tinyint (1) NOT NULL,
        `limitcomb` tinyint (1) NOT NULL,
        `limitexpiration` tinyint (1) NOT NULL,
        `limituptime` tinyint (1) NOT NULL,
        `poolname` varchar(50) NOT NULL,
        `unitprice` decimal(25, 6) NOT NULL,
        `unitpriceadd` decimal(25, 6) NOT NULL,
        `timebaseexp` tinyint (1) NOT NULL,
        `timebaseonline` tinyint (1) NOT NULL,
        `timeunitexp` int (11) NOT NULL,
        `timeunitonline` int (11) NOT NULL,
        `trafficunitdl` int (11) NOT NULL,
        `trafficunitul` int (11) NOT NULL,
        `trafficunitcomb` int (11) NOT NULL,
        `inittimeexp` int (11) NOT NULL,
        `inittimeonline` int (11) NOT NULL,
        `initdl` int (11) NOT NULL,
        `initul` int (11) NOT NULL,
        `inittotal` int (11) NOT NULL,
        `srvtype` tinyint (1) NOT NULL,
        `timeaddmodeexp` tinyint (1) NOT NULL,
        `timeaddmodeonline` tinyint (1) NOT NULL,
        `trafficaddmode` tinyint (1) NOT NULL,
        `monthly` tinyint (1) NOT NULL,
        `enaddcredits` tinyint (1) NOT NULL,
        `minamount` int (20) NOT NULL,
        `minamountadd` int (20) NOT NULL,
        `resetctrdate` tinyint (1) NOT NULL,
        `resetctrneg` tinyint (1) NOT NULL,
        `pricecalcdownload` tinyint (1) NOT NULL,
        `pricecalcupload` tinyint (1) NOT NULL,
        `pricecalcuptime` tinyint (1) NOT NULL,
        `unitpricetax` decimal(25, 6) NOT NULL,
        `unitpriceaddtax` decimal(25, 6) NOT NULL,
        `enableburst` tinyint (1) NOT NULL,
        `dlburstlimit` int (11) NOT NULL,
        `ulburstlimit` int (11) NOT NULL,
        `dlburstthreshold` int (11) NOT NULL,
        `ulburstthreshold` int (11) NOT NULL,
        `dlbursttime` int (11) NOT NULL,
        `ulbursttime` int (11) NOT NULL,
        `enableservice` int (11) NOT NULL,
        `dlquota` bigint (20) NOT NULL,
        `ulquota` bigint (20) NOT NULL,
        `combquota` bigint (20) NOT NULL,
        `timequota` bigint (20) NOT NULL,
        `priority` smallint (6) NOT NULL,
        `nextsrvid` int (11) NOT NULL,
        `dailynextsrvid` int (11) NOT NULL,
        `disnextsrvid` int (11) NOT NULL,
        `availucp` tinyint (1) NOT NULL,
        `renew` tinyint (1) NOT NULL,
        `carryover` tinyint (1) NOT NULL,
        `policymapdl` varchar(50) NOT NULL,
        `policymapul` varchar(50) NOT NULL,
        `custattr` varchar(10240) NOT NULL,
        `gentftp` tinyint (1) NOT NULL,
        `cmcfg` varchar(10240) NOT NULL,
        `advcmcfg` tinyint (1) NOT NULL,
        `addamount` int (11) NOT NULL,
        `ignstatip` tinyint (1) NOT NULL,
        PRIMARY KEY (`srvid`),
        KEY `srvname` (`srvname`)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8;