CREATE TABLE
    `rm_users` (
        `username` varchar(64) NOT NULL,
        `password` varchar(32) NOT NULL,
        `macpswmode` tinyint (1) NOT NULL,
        `groupid` int (11) NOT NULL,
        `enableuser` tinyint (1) NOT NULL,
        `uplimit` bigint (20) NOT NULL,
        `downlimit` bigint (20) NOT NULL,
        `comblimit` bigint (20) NOT NULL,
        `firstname` varchar(50) NOT NULL,
        `lastname` varchar(50) NOT NULL,
        `company` varchar(50) NOT NULL,
        `phone` varchar(15) NOT NULL,
        `mobile` varchar(15) NOT NULL,
        `address` varchar(100) NOT NULL,
        `city` varchar(50) NOT NULL,
        `zip` varchar(8) NOT NULL,
        `country` varchar(50) NOT NULL,
        `state` varchar(50) NOT NULL,
        `comment` varchar(500) NOT NULL,
        `gpslat` decimal(17, 14) NOT NULL,
        `gpslong` decimal(17, 14) NOT NULL,
        `mac` varchar(17) NOT NULL,
        `usemacauth` tinyint (1) NOT NULL,
        `expiration` datetime DEFAULT NULL,
        `uptimelimit` bigint (20) NOT NULL,
        `srvid` int (11) NOT NULL,
        `staticipcm` varchar(15) NOT NULL,
        `staticipcpe` varchar(15) NOT NULL,
        `ipmodecm` tinyint (1) NOT NULL,
        `ipmodecpe` tinyint (1) NOT NULL,
        `poolidcm` int (11) NOT NULL,
        `poolidcpe` int (11) NOT NULL,
        `createdon` date NOT NULL,
        `acctype` tinyint (1) NOT NULL,
        `credits` decimal(20, 2) NOT NULL,
        `cardfails` tinyint (4) NOT NULL,
        `createdby` varchar(64) NOT NULL,
        `owner` varchar(64) NOT NULL,
        `taxid` varchar(40) NOT NULL,
        `cnic` varchar(30) NOT NULL,
        `email` varchar(100) NOT NULL,
        `maccm` varchar(17) NOT NULL,
        `custattr` varchar(10240) NOT NULL,
        `warningsent` tinyint (1) NOT NULL,
        `verifycode` varchar(10) NOT NULL,
        `verified` tinyint (1) NOT NULL,
        `selfreg` tinyint (1) NOT NULL,
        `verifyfails` tinyint (4) NOT NULL,
        `verifysentnum` tinyint (4) NOT NULL,
        `verifymobile` varchar(15) NOT NULL,
        `contractid` varchar(50) NOT NULL,
        `contractvalid` date DEFAULT NULL,
        `actcode` varchar(60) NOT NULL,
        `pswactsmsnum` tinyint (4) NOT NULL,
        `alertemail` tinyint (1) NOT NULL,
        `alertsms` tinyint (1) NOT NULL,
        `lang` varchar(30) NOT NULL,
        `lastlogoff` datetime DEFAULT NULL,
        `autorenew` tinyint (1) NOT NULL,
        PRIMARY KEY (`username`),
        KEY `srvid` (`srvid`),
        KEY `groupid` (`groupid`),
        KEY `enableuser` (`enableuser`),
        KEY `firstname` (`firstname`),
        KEY `lastname` (`lastname`),
        KEY `company` (`company`),
        KEY `phone` (`phone`),
        KEY `mobile` (`mobile`),
        KEY `address` (`address`),
        KEY `city` (`city`),
        KEY `zip` (`zip`),
        KEY `country` (`country`),
        KEY `state` (`state`),
        KEY `comment` (`comment` (255)),
        KEY `mac` (`mac`),
        KEY `acctype` (`acctype`),
        KEY `email` (`email`),
        KEY `maccm` (`maccm`),
        KEY `owner` (`owner`),
        KEY `staticipcpe` (`staticipcpe`),
        KEY `staticipcm` (`staticipcm`),
        KEY `expiration` (`expiration`),
        KEY `createdon` (`createdon`),
        KEY `contractid` (`contractid`),
        KEY `contractvalid` (`contractvalid`),
        KEY `lastlogoff` (`lastlogoff`)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8;