// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset_requests.sql

package zing

import (
	"context"
)

const getPasswordResetRequest = `-- name: GetPasswordResetRequest :one
SELECT
    id, userid, expires, datecreated, deleted
FROM
    PasswordResetRequests
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetPasswordResetRequest(ctx context.Context, id string) (Passwordresetrequest, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetRequest, id)
	var i Passwordresetrequest
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Expires,
		&i.Datecreated,
		&i.Deleted,
	)
	return i, err
}

const getPasswordResetRequests = `-- name: GetPasswordResetRequests :many
SELECT
    id, userid, expires, datecreated, deleted
FROM
    PasswordResetRequests
LIMIT
    ?
OFFSET
    ?
`

type GetPasswordResetRequestsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetPasswordResetRequests(ctx context.Context, arg GetPasswordResetRequestsParams) ([]Passwordresetrequest, error) {
	rows, err := q.db.QueryContext(ctx, getPasswordResetRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passwordresetrequest
	for rows.Next() {
		var i Passwordresetrequest
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.Expires,
			&i.Datecreated,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
