// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_requests.sql

package zing

import (
	"context"
)

const getPaymentRequest = `-- name: GetPaymentRequest :one
SELECT
    id, customerid, productid, datecreated
FROM
    PaymentRequests
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetPaymentRequest(ctx context.Context, id int64) (Paymentrequest, error) {
	row := q.db.QueryRowContext(ctx, getPaymentRequest, id)
	var i Paymentrequest
	err := row.Scan(
		&i.ID,
		&i.Customerid,
		&i.Productid,
		&i.Datecreated,
	)
	return i, err
}

const getPaymentRequests = `-- name: GetPaymentRequests :many
SELECT
    id, customerid, productid, datecreated
FROM
    PaymentRequests
LIMIT
    ?
OFFSET
    ?
`

type GetPaymentRequestsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetPaymentRequests(ctx context.Context, arg GetPaymentRequestsParams) ([]Paymentrequest, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paymentrequest
	for rows.Next() {
		var i Paymentrequest
		if err := rows.Scan(
			&i.ID,
			&i.Customerid,
			&i.Productid,
			&i.Datecreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
