// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: roles.sql

package zing

import (
	"context"
)

const getRole = `-- name: GetRole :one
SELECT
    id, name, createdbyuserid, datecreated, deleted
FROM
    Roles
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetRole(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Createdbyuserid,
		&i.Datecreated,
		&i.Deleted,
	)
	return i, err
}

const getRoles = `-- name: GetRoles :many
SELECT
    id, name, createdbyuserid, datecreated, deleted
FROM
    Roles
LIMIT
    ?
OFFSET
    ?
`

type GetRolesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetRoles(ctx context.Context, arg GetRolesParams) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Createdbyuserid,
			&i.Datecreated,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
