// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rm_allowedmanagers.sql

package radius

import (
	"context"
)

const getRmAllowedmanager = `-- name: GetRmAllowedmanager :one
SELECT
    srvid, managername
FROM
    rm_allowedmanagers
WHERE
    srvid = ?
LIMIT
    1
`

func (q *Queries) GetRmAllowedmanager(ctx context.Context, srvid int32) (RmAllowedmanager, error) {
	row := q.db.QueryRowContext(ctx, getRmAllowedmanager, srvid)
	var i RmAllowedmanager
	err := row.Scan(&i.Srvid, &i.Managername)
	return i, err
}

const getRmAllowedmanagers = `-- name: GetRmAllowedmanagers :many
SELECT
    srvid, managername
FROM
    rm_allowedmanagers
LIMIT
    ?
OFFSET
    ?
`

type GetRmAllowedmanagersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetRmAllowedmanagers(ctx context.Context, arg GetRmAllowedmanagersParams) ([]RmAllowedmanager, error) {
	rows, err := q.db.QueryContext(ctx, getRmAllowedmanagers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RmAllowedmanager
	for rows.Next() {
		var i RmAllowedmanager
		if err := rows.Scan(&i.Srvid, &i.Managername); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
