// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rm_colsetlistradius.sql

package radius

import (
	"context"
)

const getRmColsetlistradius = `-- name: GetRmColsetlistradius :one
SELECT
    managername, colname
FROM
    rm_colsetlistradius
WHERE
    managername = ?
LIMIT
    1
`

func (q *Queries) GetRmColsetlistradius(ctx context.Context, managername string) (RmColsetlistradiu, error) {
	row := q.db.QueryRowContext(ctx, getRmColsetlistradius, managername)
	var i RmColsetlistradiu
	err := row.Scan(&i.Managername, &i.Colname)
	return i, err
}

const getRmColsetlistradiuses = `-- name: GetRmColsetlistradiuses :many
SELECT
    managername, colname
FROM
    rm_colsetlistradius
LIMIT
    ?
OFFSET
    ?
`

type GetRmColsetlistradiusesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetRmColsetlistradiuses(ctx context.Context, arg GetRmColsetlistradiusesParams) ([]RmColsetlistradiu, error) {
	rows, err := q.db.QueryContext(ctx, getRmColsetlistradiuses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RmColsetlistradiu
	for rows.Next() {
		var i RmColsetlistradiu
		if err := rows.Scan(&i.Managername, &i.Colname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
