// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rm_radacct.sql

package radius

import (
	"context"
)

const getRmRadacct = `-- name: GetRmRadacct :one
SELECT
    radacctid, acctuniqueid, username, acctstarttime, acctstoptime, acctsessiontime, acctsessiontimeratio, dlbytesstart, dlbytesstop, dlbytes, dlratio, ulbytesstart, ulbytesstop, ulbytes, ulratio
FROM
    rm_radacct
WHERE
    radacctid = ?
LIMIT
    1
`

func (q *Queries) GetRmRadacct(ctx context.Context, radacctid int64) (RmRadacct, error) {
	row := q.db.QueryRowContext(ctx, getRmRadacct, radacctid)
	var i RmRadacct
	err := row.Scan(
		&i.Radacctid,
		&i.Acctuniqueid,
		&i.Username,
		&i.Acctstarttime,
		&i.Acctstoptime,
		&i.Acctsessiontime,
		&i.Acctsessiontimeratio,
		&i.Dlbytesstart,
		&i.Dlbytesstop,
		&i.Dlbytes,
		&i.Dlratio,
		&i.Ulbytesstart,
		&i.Ulbytesstop,
		&i.Ulbytes,
		&i.Ulratio,
	)
	return i, err
}

const getRmRadaccts = `-- name: GetRmRadaccts :many
SELECT
    radacctid, acctuniqueid, username, acctstarttime, acctstoptime, acctsessiontime, acctsessiontimeratio, dlbytesstart, dlbytesstop, dlbytes, dlratio, ulbytesstart, ulbytesstop, ulbytes, ulratio
FROM
    rm_radacct
LIMIT
    ?
OFFSET
    ?
`

type GetRmRadacctsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetRmRadaccts(ctx context.Context, arg GetRmRadacctsParams) ([]RmRadacct, error) {
	rows, err := q.db.QueryContext(ctx, getRmRadaccts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RmRadacct
	for rows.Next() {
		var i RmRadacct
		if err := rows.Scan(
			&i.Radacctid,
			&i.Acctuniqueid,
			&i.Username,
			&i.Acctstarttime,
			&i.Acctstoptime,
			&i.Acctsessiontime,
			&i.Acctsessiontimeratio,
			&i.Dlbytesstart,
			&i.Dlbytesstop,
			&i.Dlbytes,
			&i.Dlratio,
			&i.Ulbytesstart,
			&i.Ulbytesstop,
			&i.Ulbytes,
			&i.Ulratio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
