// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rm_wlan.sql

package radius

import (
	"context"
	"database/sql"
)

const getRmWlan = `-- name: GetRmWlan :one
SELECT
    maccpe, uspwr, ccq, snr, apip, timestamp
FROM
    rm_wlan
WHERE
    maccpe = ?
LIMIT
    1
`

func (q *Queries) GetRmWlan(ctx context.Context, maccpe sql.NullString) (RmWlan, error) {
	row := q.db.QueryRowContext(ctx, getRmWlan, maccpe)
	var i RmWlan
	err := row.Scan(
		&i.Maccpe,
		&i.Uspwr,
		&i.Ccq,
		&i.Snr,
		&i.Apip,
		&i.Timestamp,
	)
	return i, err
}

const getRmWlans = `-- name: GetRmWlans :many
SELECT
    maccpe, uspwr, ccq, snr, apip, timestamp
FROM
    rm_wlan
LIMIT
    ?
OFFSET
    ?
`

type GetRmWlansParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetRmWlans(ctx context.Context, arg GetRmWlansParams) ([]RmWlan, error) {
	rows, err := q.db.QueryContext(ctx, getRmWlans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RmWlan
	for rows.Next() {
		var i RmWlan
		if err := rows.Scan(
			&i.Maccpe,
			&i.Uspwr,
			&i.Ccq,
			&i.Snr,
			&i.Apip,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
