/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersIdRouteImport } from './routes/users/$id'
import { Route as ReportsSummaryRouteImport } from './routes/reports/summary'
import { Route as ReportsRechargesSummaryRouteImport } from './routes/reports/recharges-summary'
import { Route as ReportsRechargesRouteImport } from './routes/reports/recharges'
import { Route as ReportsExpiringCustomersRouteImport } from './routes/reports/expiring-customers'
import { Route as ReportsCustomersRouteImport } from './routes/reports/customers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSummaryRoute = ReportsSummaryRouteImport.update({
  id: '/reports/summary',
  path: '/reports/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRechargesSummaryRoute = ReportsRechargesSummaryRouteImport.update({
  id: '/reports/recharges-summary',
  path: '/reports/recharges-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRechargesRoute = ReportsRechargesRouteImport.update({
  id: '/reports/recharges',
  path: '/reports/recharges',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsExpiringCustomersRoute =
  ReportsExpiringCustomersRouteImport.update({
    id: '/reports/expiring-customers',
    path: '/reports/expiring-customers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsCustomersRoute = ReportsCustomersRouteImport.update({
  id: '/reports/customers',
  path: '/reports/customers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports/customers': typeof ReportsCustomersRoute
  '/reports/expiring-customers': typeof ReportsExpiringCustomersRoute
  '/reports/recharges': typeof ReportsRechargesRoute
  '/reports/recharges-summary': typeof ReportsRechargesSummaryRoute
  '/reports/summary': typeof ReportsSummaryRoute
  '/users/$id': typeof UsersIdRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports/customers': typeof ReportsCustomersRoute
  '/reports/expiring-customers': typeof ReportsExpiringCustomersRoute
  '/reports/recharges': typeof ReportsRechargesRoute
  '/reports/recharges-summary': typeof ReportsRechargesSummaryRoute
  '/reports/summary': typeof ReportsSummaryRoute
  '/users/$id': typeof UsersIdRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports/customers': typeof ReportsCustomersRoute
  '/reports/expiring-customers': typeof ReportsExpiringCustomersRoute
  '/reports/recharges': typeof ReportsRechargesRoute
  '/reports/recharges-summary': typeof ReportsRechargesSummaryRoute
  '/reports/summary': typeof ReportsSummaryRoute
  '/users/$id': typeof UsersIdRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports/customers'
    | '/reports/expiring-customers'
    | '/reports/recharges'
    | '/reports/recharges-summary'
    | '/reports/summary'
    | '/users/$id'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reports/customers'
    | '/reports/expiring-customers'
    | '/reports/recharges'
    | '/reports/recharges-summary'
    | '/reports/summary'
    | '/users/$id'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/reports/customers'
    | '/reports/expiring-customers'
    | '/reports/recharges'
    | '/reports/recharges-summary'
    | '/reports/summary'
    | '/users/$id'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsCustomersRoute: typeof ReportsCustomersRoute
  ReportsExpiringCustomersRoute: typeof ReportsExpiringCustomersRoute
  ReportsRechargesRoute: typeof ReportsRechargesRoute
  ReportsRechargesSummaryRoute: typeof ReportsRechargesSummaryRoute
  ReportsSummaryRoute: typeof ReportsSummaryRoute
  UsersIdRoute: typeof UsersIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/summary': {
      id: '/reports/summary'
      path: '/reports/summary'
      fullPath: '/reports/summary'
      preLoaderRoute: typeof ReportsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/recharges-summary': {
      id: '/reports/recharges-summary'
      path: '/reports/recharges-summary'
      fullPath: '/reports/recharges-summary'
      preLoaderRoute: typeof ReportsRechargesSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/recharges': {
      id: '/reports/recharges'
      path: '/reports/recharges'
      fullPath: '/reports/recharges'
      preLoaderRoute: typeof ReportsRechargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/expiring-customers': {
      id: '/reports/expiring-customers'
      path: '/reports/expiring-customers'
      fullPath: '/reports/expiring-customers'
      preLoaderRoute: typeof ReportsExpiringCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/customers': {
      id: '/reports/customers'
      path: '/reports/customers'
      fullPath: '/reports/customers'
      preLoaderRoute: typeof ReportsCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsCustomersRoute: ReportsCustomersRoute,
  ReportsExpiringCustomersRoute: ReportsExpiringCustomersRoute,
  ReportsRechargesRoute: ReportsRechargesRoute,
  ReportsRechargesSummaryRoute: ReportsRechargesSummaryRoute,
  ReportsSummaryRoute: ReportsSummaryRoute,
  UsersIdRoute: UsersIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
