/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as PoisIndexRouteImport } from './routes/pois/index'
import { Route as UsersIdRouteImport } from './routes/users/$id'
import { Route as PoisIdRouteImport } from './routes/pois/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoisIndexRoute = PoisIndexRouteImport.update({
  id: '/pois/',
  path: '/pois/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PoisIdRoute = PoisIdRouteImport.update({
  id: '/pois/$id',
  path: '/pois/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pois/$id': typeof PoisIdRoute
  '/users/$id': typeof UsersIdRoute
  '/pois': typeof PoisIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pois/$id': typeof PoisIdRoute
  '/users/$id': typeof UsersIdRoute
  '/pois': typeof PoisIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pois/$id': typeof PoisIdRoute
  '/users/$id': typeof UsersIdRoute
  '/pois/': typeof PoisIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pois/$id' | '/users/$id' | '/pois' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pois/$id' | '/users/$id' | '/pois' | '/users'
  id: '__root__' | '/' | '/pois/$id' | '/users/$id' | '/pois/' | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoisIdRoute: typeof PoisIdRoute
  UsersIdRoute: typeof UsersIdRoute
  PoisIndexRoute: typeof PoisIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pois/': {
      id: '/pois/'
      path: '/pois'
      fullPath: '/pois'
      preLoaderRoute: typeof PoisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pois/$id': {
      id: '/pois/$id'
      path: '/pois/$id'
      fullPath: '/pois/$id'
      preLoaderRoute: typeof PoisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoisIdRoute: PoisIdRoute,
  UsersIdRoute: UsersIdRoute,
  PoisIndexRoute: PoisIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
