// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dynamic_queries_child_queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createDynamicQueryChildQuery = `-- name: CreateDynamicQueryChildQuery :one
INSERT INTO
    dynamic_query_child_queries (
        dynamic_query_id,
        child_query_id
    )
VALUES
    ($1, $2)
RETURNING dynamic_query_id, child_query_id
`

type CreateDynamicQueryChildQueryParams struct {
	DynamicQueryID uuid.UUID
	ChildQueryID   uuid.UUID
}

func (q *Queries) CreateDynamicQueryChildQuery(ctx context.Context, arg CreateDynamicQueryChildQueryParams) (DynamicQueryChildQuery, error) {
	row := q.db.QueryRow(ctx, createDynamicQueryChildQuery, arg.DynamicQueryID, arg.ChildQueryID)
	var i DynamicQueryChildQuery
	err := row.Scan(&i.DynamicQueryID, &i.ChildQueryID)
	return i, err
}
