// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dynamic_queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDynamicQuery = `-- name: CreateDynamicQuery :one
INSERT INTO
    dynamic_queries (
        name,
        query,
        response_id
    )
VALUES
    ($1, $2, $3) RETURNING id, name, query, response_id, created_at, updated_at
`

type CreateDynamicQueryParams struct {
	Name       string
	Query      pgtype.Text
	ResponseID pgtype.Text
}

func (q *Queries) CreateDynamicQuery(ctx context.Context, arg CreateDynamicQueryParams) (DynamicQuery, error) {
	row := q.db.QueryRow(ctx, createDynamicQuery, arg.Name, arg.Query, arg.ResponseID)
	var i DynamicQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.ResponseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDynamicQuery = `-- name: DeleteDynamicQuery :one
DELETE FROM dynamic_queries
WHERE
    id = $1 RETURNING id, name, query, response_id, created_at, updated_at
`

func (q *Queries) DeleteDynamicQuery(ctx context.Context, id uuid.UUID) (DynamicQuery, error) {
	row := q.db.QueryRow(ctx, deleteDynamicQuery, id)
	var i DynamicQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.ResponseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDynamicQueries = `-- name: GetDynamicQueries :many
SELECT
    id, name, query, response_id, created_at, updated_at
FROM
    dynamic_queries
WHERE
    TRIM(LOWER(name)) ILIKE '%' || TRIM(LOWER($3::text)) || '%'
ORDER BY
    name ASC
LIMIT $1
OFFSET $2
`

type GetDynamicQueriesParams struct {
	Limit      int32
	Offset     int32
	SearchTerm string
}

func (q *Queries) GetDynamicQueries(ctx context.Context, arg GetDynamicQueriesParams) ([]DynamicQuery, error) {
	rows, err := q.db.Query(ctx, getDynamicQueries, arg.Limit, arg.Offset, arg.SearchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DynamicQuery
	for rows.Next() {
		var i DynamicQuery
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Query,
			&i.ResponseID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDynamicQuery = `-- name: GetDynamicQuery :one
SELECT
    id, name, query, response_id, created_at, updated_at
FROM
    dynamic_queries
WHERE
    id = $1
LIMIT
    1
`

func (q *Queries) GetDynamicQuery(ctx context.Context, id uuid.UUID) (DynamicQuery, error) {
	row := q.db.QueryRow(ctx, getDynamicQuery, id)
	var i DynamicQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.ResponseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTotalDynamicQueries = `-- name: GetTotalDynamicQueries :one
SELECT
    COUNT(*) AS total
FROM
    dynamic_queries
LIMIT
    1
`

func (q *Queries) GetTotalDynamicQueries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalDynamicQueries)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateDynamicQuery = `-- name: UpdateDynamicQuery :one
UPDATE dynamic_queries
SET
    name = $1,
    query = $2,
    response_id = $3,
    updated_at = NOW()
WHERE
    id = $4 RETURNING id, name, query, response_id, created_at, updated_at
`

type UpdateDynamicQueryParams struct {
	Name       string
	Query      pgtype.Text
	ResponseID pgtype.Text
	ID         uuid.UUID
}

func (q *Queries) UpdateDynamicQuery(ctx context.Context, arg UpdateDynamicQueryParams) (DynamicQuery, error) {
	row := q.db.QueryRow(ctx, updateDynamicQuery,
		arg.Name,
		arg.Query,
		arg.ResponseID,
		arg.ID,
	)
	var i DynamicQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.ResponseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
