// This file is auto-generated by @hey-api/openapi-ts
import {
  type InfiniteData,
  type UseMutationOptions,
  infiniteQueryOptions,
  queryOptions,
} from '@tanstack/react-query';

import { client as _heyApiClient } from '../client.gen';
import {
  type Options,
  deleteApiPoisById,
  deleteApiUsersById,
  getApiAuthenticationCheck,
  getApiAuthenticationMfaEnable,
  getApiPois,
  getApiPoisById,
  getApiUsers,
  getApiUsersById,
  postApiAuthenticationLogin,
  postApiAuthenticationLogout,
  postApiAuthenticationMfaDisable,
  postApiAuthenticationMfaVerify,
  postApiAuthenticationRegister,
  postApiPois,
  postApiUsers,
  putApiPoisById,
  putApiUsersById,
} from '../sdk.gen';
import type {
  DeleteApiPoisByIdData,
  DeleteApiPoisByIdError,
  DeleteApiPoisByIdResponse,
  DeleteApiUsersByIdData,
  DeleteApiUsersByIdError,
  DeleteApiUsersByIdResponse,
  GetApiAuthenticationCheckData,
  GetApiAuthenticationMfaEnableData,
  GetApiPoisByIdData,
  GetApiPoisData,
  GetApiPoisError,
  GetApiPoisResponse,
  GetApiUsersByIdData,
  GetApiUsersData,
  GetApiUsersError,
  GetApiUsersResponse,
  PostApiAuthenticationLoginData,
  PostApiAuthenticationLoginError,
  PostApiAuthenticationLoginResponse,
  PostApiAuthenticationLogoutData,
  PostApiAuthenticationLogoutError,
  PostApiAuthenticationLogoutResponse,
  PostApiAuthenticationMfaDisableData,
  PostApiAuthenticationMfaDisableError,
  PostApiAuthenticationMfaDisableResponse,
  PostApiAuthenticationMfaVerifyData,
  PostApiAuthenticationMfaVerifyError,
  PostApiAuthenticationMfaVerifyResponse,
  PostApiAuthenticationRegisterData,
  PostApiAuthenticationRegisterError,
  PostApiAuthenticationRegisterResponse,
  PostApiPoisData,
  PostApiPoisError,
  PostApiPoisResponse,
  PostApiUsersData,
  PostApiUsersError,
  PostApiUsersResponse,
  PutApiPoisByIdData,
  PutApiPoisByIdError,
  PutApiPoisByIdResponse,
  PutApiUsersByIdData,
  PutApiUsersByIdError,
  PutApiUsersByIdResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getApiAuthenticationCheckQueryKey = (
  options?: Options<GetApiAuthenticationCheckData>
) => createQueryKey('getApiAuthenticationCheck', options);

/**
 * Check Authentication
 * Endpoint to check if the user is authenticated
 */
export const getApiAuthenticationCheckOptions = (
  options?: Options<GetApiAuthenticationCheckData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAuthenticationCheck({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiAuthenticationCheckQueryKey(options),
  });
};

export const postApiAuthenticationLoginQueryKey = (
  options?: Options<PostApiAuthenticationLoginData>
) => createQueryKey('postApiAuthenticationLogin', options);

/**
 * Login
 * Endpoint for user login
 */
export const postApiAuthenticationLoginOptions = (
  options?: Options<PostApiAuthenticationLoginData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiAuthenticationLogin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiAuthenticationLoginQueryKey(options),
  });
};

/**
 * Login
 * Endpoint for user login
 */
export const postApiAuthenticationLoginMutation = (
  options?: Partial<Options<PostApiAuthenticationLoginData>>
): UseMutationOptions<
  PostApiAuthenticationLoginResponse,
  PostApiAuthenticationLoginError,
  Options<PostApiAuthenticationLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthenticationLoginResponse,
    PostApiAuthenticationLoginError,
    Options<PostApiAuthenticationLoginData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiAuthenticationLogin({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiAuthenticationLogoutQueryKey = (
  options?: Options<PostApiAuthenticationLogoutData>
) => createQueryKey('postApiAuthenticationLogout', options);

/**
 * Logout
 * Endpoint for user logout
 */
export const postApiAuthenticationLogoutOptions = (
  options?: Options<PostApiAuthenticationLogoutData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiAuthenticationLogout({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiAuthenticationLogoutQueryKey(options),
  });
};

/**
 * Logout
 * Endpoint for user logout
 */
export const postApiAuthenticationLogoutMutation = (
  options?: Partial<Options<PostApiAuthenticationLogoutData>>
): UseMutationOptions<
  PostApiAuthenticationLogoutResponse,
  PostApiAuthenticationLogoutError,
  Options<PostApiAuthenticationLogoutData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthenticationLogoutResponse,
    PostApiAuthenticationLogoutError,
    Options<PostApiAuthenticationLogoutData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiAuthenticationLogout({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiAuthenticationMfaDisableQueryKey = (
  options?: Options<PostApiAuthenticationMfaDisableData>
) => createQueryKey('postApiAuthenticationMfaDisable', options);

/**
 * Disable MFA
 * Endpoint to disable multi-factor authentication
 */
export const postApiAuthenticationMfaDisableOptions = (
  options?: Options<PostApiAuthenticationMfaDisableData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiAuthenticationMfaDisable({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiAuthenticationMfaDisableQueryKey(options),
  });
};

/**
 * Disable MFA
 * Endpoint to disable multi-factor authentication
 */
export const postApiAuthenticationMfaDisableMutation = (
  options?: Partial<Options<PostApiAuthenticationMfaDisableData>>
): UseMutationOptions<
  PostApiAuthenticationMfaDisableResponse,
  PostApiAuthenticationMfaDisableError,
  Options<PostApiAuthenticationMfaDisableData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthenticationMfaDisableResponse,
    PostApiAuthenticationMfaDisableError,
    Options<PostApiAuthenticationMfaDisableData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiAuthenticationMfaDisable({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiAuthenticationMfaEnableQueryKey = (
  options?: Options<GetApiAuthenticationMfaEnableData>
) => createQueryKey('getApiAuthenticationMfaEnable', options);

/**
 * Enable MFA
 * Endpoint to enable multi-factor authentication
 */
export const getApiAuthenticationMfaEnableOptions = (
  options?: Options<GetApiAuthenticationMfaEnableData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAuthenticationMfaEnable({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiAuthenticationMfaEnableQueryKey(options),
  });
};

export const postApiAuthenticationMfaVerifyQueryKey = (
  options?: Options<PostApiAuthenticationMfaVerifyData>
) => createQueryKey('postApiAuthenticationMfaVerify', options);

/**
 * Verify MFA
 * Endpoint to verify multi-factor authentication code
 */
export const postApiAuthenticationMfaVerifyOptions = (
  options?: Options<PostApiAuthenticationMfaVerifyData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiAuthenticationMfaVerify({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiAuthenticationMfaVerifyQueryKey(options),
  });
};

/**
 * Verify MFA
 * Endpoint to verify multi-factor authentication code
 */
export const postApiAuthenticationMfaVerifyMutation = (
  options?: Partial<Options<PostApiAuthenticationMfaVerifyData>>
): UseMutationOptions<
  PostApiAuthenticationMfaVerifyResponse,
  PostApiAuthenticationMfaVerifyError,
  Options<PostApiAuthenticationMfaVerifyData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthenticationMfaVerifyResponse,
    PostApiAuthenticationMfaVerifyError,
    Options<PostApiAuthenticationMfaVerifyData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiAuthenticationMfaVerify({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiAuthenticationRegisterQueryKey = (
  options?: Options<PostApiAuthenticationRegisterData>
) => createQueryKey('postApiAuthenticationRegister', options);

/**
 * Register
 * Endpoint for user registration
 */
export const postApiAuthenticationRegisterOptions = (
  options?: Options<PostApiAuthenticationRegisterData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiAuthenticationRegister({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiAuthenticationRegisterQueryKey(options),
  });
};

/**
 * Register
 * Endpoint for user registration
 */
export const postApiAuthenticationRegisterMutation = (
  options?: Partial<Options<PostApiAuthenticationRegisterData>>
): UseMutationOptions<
  PostApiAuthenticationRegisterResponse,
  PostApiAuthenticationRegisterError,
  Options<PostApiAuthenticationRegisterData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthenticationRegisterResponse,
    PostApiAuthenticationRegisterError,
    Options<PostApiAuthenticationRegisterData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiAuthenticationRegister({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiPoisQueryKey = (options?: Options<GetApiPoisData>) =>
  createQueryKey('getApiPois', options);

/**
 * Get Points Of Interest
 * Endpoint to retrieve a list of points of interest
 */
export const getApiPoisOptions = (options?: Options<GetApiPoisData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPois({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiPoisQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = {
    ...queryKey[0],
  };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getApiPoisInfiniteQueryKey = (
  options?: Options<GetApiPoisData>
): QueryKey<Options<GetApiPoisData>> =>
  createQueryKey('getApiPois', options, true);

/**
 * Get Points Of Interest
 * Endpoint to retrieve a list of points of interest
 */
export const getApiPoisInfiniteOptions = (
  options?: Options<GetApiPoisData>
) => {
  return infiniteQueryOptions<
    GetApiPoisResponse,
    GetApiPoisError,
    InfiniteData<GetApiPoisResponse>,
    QueryKey<Options<GetApiPoisData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiPoisData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiPoisData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiPois({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiPoisInfiniteQueryKey(options),
    }
  );
};

export const postApiPoisQueryKey = (options?: Options<PostApiPoisData>) =>
  createQueryKey('postApiPois', options);

/**
 * Create Point Of Interest
 * Endpoint to create a new point of interest
 */
export const postApiPoisOptions = (options?: Options<PostApiPoisData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiPois({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiPoisQueryKey(options),
  });
};

/**
 * Create Point Of Interest
 * Endpoint to create a new point of interest
 */
export const postApiPoisMutation = (
  options?: Partial<Options<PostApiPoisData>>
): UseMutationOptions<
  PostApiPoisResponse,
  PostApiPoisError,
  Options<PostApiPoisData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiPoisResponse,
    PostApiPoisError,
    Options<PostApiPoisData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiPois({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Point Of Interest
 * Endpoint to delete a point of interest by ID
 */
export const deleteApiPoisByIdMutation = (
  options?: Partial<Options<DeleteApiPoisByIdData>>
): UseMutationOptions<
  DeleteApiPoisByIdResponse,
  DeleteApiPoisByIdError,
  Options<DeleteApiPoisByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiPoisByIdResponse,
    DeleteApiPoisByIdError,
    Options<DeleteApiPoisByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteApiPoisById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiPoisByIdQueryKey = (options: Options<GetApiPoisByIdData>) =>
  createQueryKey('getApiPoisById', options);

/**
 * Get Point Of Interest
 * Endpoint to retrieve a point of interest by ID
 */
export const getApiPoisByIdOptions = (options: Options<GetApiPoisByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPoisById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiPoisByIdQueryKey(options),
  });
};

/**
 * Update Point Of Interest
 * Endpoint to update an existing point of interest
 */
export const putApiPoisByIdMutation = (
  options?: Partial<Options<PutApiPoisByIdData>>
): UseMutationOptions<
  PutApiPoisByIdResponse,
  PutApiPoisByIdError,
  Options<PutApiPoisByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiPoisByIdResponse,
    PutApiPoisByIdError,
    Options<PutApiPoisByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await putApiPoisById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiUsersQueryKey = (options?: Options<GetApiUsersData>) =>
  createQueryKey('getApiUsers', options);

/**
 * Get Users
 * Endpoint to retrieve a list of users
 */
export const getApiUsersOptions = (options?: Options<GetApiUsersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiUsersQueryKey(options),
  });
};

export const getApiUsersInfiniteQueryKey = (
  options?: Options<GetApiUsersData>
): QueryKey<Options<GetApiUsersData>> =>
  createQueryKey('getApiUsers', options, true);

/**
 * Get Users
 * Endpoint to retrieve a list of users
 */
export const getApiUsersInfiniteOptions = (
  options?: Options<GetApiUsersData>
) => {
  return infiniteQueryOptions<
    GetApiUsersResponse,
    GetApiUsersError,
    InfiniteData<GetApiUsersResponse>,
    QueryKey<Options<GetApiUsersData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiUsersData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiUsersData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiUsersInfiniteQueryKey(options),
    }
  );
};

export const postApiUsersQueryKey = (options?: Options<PostApiUsersData>) =>
  createQueryKey('postApiUsers', options);

/**
 * Create User
 * Endpoint to create a new user
 */
export const postApiUsersOptions = (options?: Options<PostApiUsersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiUsersQueryKey(options),
  });
};

/**
 * Create User
 * Endpoint to create a new user
 */
export const postApiUsersMutation = (
  options?: Partial<Options<PostApiUsersData>>
): UseMutationOptions<
  PostApiUsersResponse,
  PostApiUsersError,
  Options<PostApiUsersData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiUsersResponse,
    PostApiUsersError,
    Options<PostApiUsersData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiUsers({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete User
 * Endpoint to delete a user by ID
 */
export const deleteApiUsersByIdMutation = (
  options?: Partial<Options<DeleteApiUsersByIdData>>
): UseMutationOptions<
  DeleteApiUsersByIdResponse,
  DeleteApiUsersByIdError,
  Options<DeleteApiUsersByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiUsersByIdResponse,
    DeleteApiUsersByIdError,
    Options<DeleteApiUsersByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteApiUsersById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiUsersByIdQueryKey = (
  options: Options<GetApiUsersByIdData>
) => createQueryKey('getApiUsersById', options);

/**
 * Get User
 * Endpoint to retrieve a user by ID
 */
export const getApiUsersByIdOptions = (
  options: Options<GetApiUsersByIdData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiUsersById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiUsersByIdQueryKey(options),
  });
};

/**
 * Update User
 * Endpoint to update an existing user
 */
export const putApiUsersByIdMutation = (
  options?: Partial<Options<PutApiUsersByIdData>>
): UseMutationOptions<
  PutApiUsersByIdResponse,
  PutApiUsersByIdError,
  Options<PutApiUsersByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiUsersByIdResponse,
    PutApiUsersByIdError,
    Options<PutApiUsersByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await putApiUsersById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
